name: Build
on: [push, pull_request]

jobs:
  build:
    name: Continous Integration
    runs-on: ubuntu-latest
    env:
      SCRIPTS_PATH: .github/workflows/scripts/register_buildpack
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ${{env.SCRIPTS_PATH}}
        shell: bash
        run: |
          npm install
      - name: Run tests
        working-directory: ${{env.SCRIPTS_PATH}}
        shell: bash
        run: |
          npm test
